package rules

// Catalog returns the full list of built-in rules in the
// order they should be considered. Each rule is
// instantiated via its newXxxRule() factory so that
// dependencies can be wired in later without touching
// Catalog's signature.
//
// Adding a new rule means adding its constructor to this
// slice. The list is the authoritative inventory of what
// the linter checks.
func Catalog() []Rule {
	return []Rule{
		newEventNameWithAggregatePrefixRule(),
		newAggregateWithoutEventsRule(),
		newAggregateWithoutCommandsRule(),
		newEventWithoutConsumerRule(),
		newEventWithoutPublisherRule(),
		newBoundedContextWithoutConsistencyUnitRule(),
		newDomainWithoutBoundedContextRule(),
		newOrphanExternalSystemRule(),
		newProcessManagerWithoutEventReactionsRule(),
		newReadModelWithoutQueryRule(),
		newOrphanActorRule(),
		newCrossAggregateCommandEmissionRule(),
		newAggregateIdentifiedByFieldRule(),
		newDynamicConsistencyBoundaryIdentifiedByFieldRule(),
		newProcessManagerCorrelatedByFieldRule(),
		newProcessManagerTimerAtFieldRule(),
		newCrossBoundedContextReferenceWithoutMappingRule(),
		newOrphanContextMappingRule(),
		newSubdomainWithoutBoundedContextRule(),
		newReadModelWithoutProjectionsRule(),
		newAggregateWithoutIdentifiedByRule(),
		newAggregateWithoutStateRule(),
		newDynamicConsistencyBoundaryWithoutIdentifiedByRule(),
		newDynamicConsistencyBoundaryWithoutConsultsRule(),
		newCommandWithoutDataRule(),
		newCommandWithoutPublishesRule(),
		newEventWithoutDataRule(),
		newEventHandlerWithoutHandlesRule(),
		newEventHandlerWithoutSideEffectsRule(),
		newPolicyWithoutHandlesRule(),
		newPolicyWithoutEmitsRule(),
		newProcessManagerWithoutStartsWhenRule(),
		newProcessManagerWithoutEndsWhenRule(),
		newDomainServiceWithoutFunctionsRule(),
		newQueryWithoutResultRule(),
		newQueryWithoutReadModelRule(),
		newReadModelWithoutSchemaRule(),
		newValueObjectWithoutSchemaRule(),
		newEntityWithoutIdentifiedByRule(),
		newEntityWithoutSchemaRule(),
		newEntityIdentifiedByFieldRule(),
		newActorWithoutTypeRule(),
		newExternalSystemWithoutDirectionRule(),
		newConsumerAtLeastOnceWithoutIdempotencyRule(),
		newHumanActorWithBackedByRule(),
		newStoryWithoutSentencesRule(),
		newStorySentenceWithoutEdgesRule(),
		newStoryOrphanActorRule(),
		newStoryOrphanWorkObjectRule(),
		newStoryOrphanGroupRule(),
		newStoryUnknownGroupMembershipRule(),
		newStoryDuplicateActorNameRule(),
		newStoryDuplicateGroupNameRule(),
		newStoryDuplicateWorkObjectInSentenceRule(),
		newFeatureWithoutScenariosRule(),
		newScenarioWithoutWhenRule(),
		newScenarioWithoutThenRule(),
		newFeatureReferencesUnknownAggregateRule(),
		newFeatureReferencesUnknownDynamicConsistencyBoundaryRule(),
		newFeatureReferencesUnknownProcessManagerRule(),
		newFeatureReferencesUnknownReadModelRule(),
		newScenarioReferencesUnknownEventRule(),
		newScenarioReferencesUnknownCommandRule(),
		newScenarioReferencesUnknownQueryRule(),
		newScenarioReferencesUnknownTimerRule(),
		newScenarioReferencesUnknownActorRule(),
		newScenarioActorNotPermittedRule(),
		newScenarioRejectionReferencesUnknownInvariantRule(),
		newUncoveredInvariantRule(),
		newScenarioWhenMismatchedFeatureScopeRule(),
		newScenarioThenMismatchedFeatureScopeRule(),
	}
}
