name: Release preview

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release preview
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Clone repository
        uses: actions/checkout@v7
        with:
          fetch-depth: '0'
      - name: Use Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version-file: ./go.mod
      - name: Run QA
        run: make qa WITH_RACE_DETECTION=true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.2.0
      - name: Login to GitHub container registry
        uses: docker/login-action@v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub registry
        uses: docker/login-action@v4.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Generate version.json
        run: make generate-version-json
      - name: Build and push documentation
        uses: docker/build-push-action@v7.3.0
        with:
          context: ./documentation/
          platforms: linux/amd64,linux/arm64
          provenance: mode=max
          sbom: true
          push: true
          tags: |
            ghcr.io/thenativeweb/esdm-documentation:preview
            thenativeweb/esdm-documentation:preview
      - name: Build and push schema host
        uses: docker/build-push-action@v7.3.0
        with:
          context: ./schema/
          platforms: linux/amd64,linux/arm64
          provenance: mode=max
          sbom: true
          push: true
          tags: |
            ghcr.io/thenativeweb/esdm-schema:preview
            thenativeweb/esdm-schema:preview
